Homework 6
infinum-academy/js-react-academy-2024-korejur pull request #6
Opened 2024-07-22 08:49 UTC by korejur

zadaća kojoj sam se najviše veselila, na kraju mi je najgora dosad :')

**napomena:** fokusirala sam se na to da odradim točno ono što je zadano u zadacima na classroomu pa nisam previše išla prilagođavati dizajn po figmi. mislim da ima puno stvari za ispraviti, ali to bih ostavila za kad se vratim u Zagreb jer se baš gubim u svemu ovome i ode mi puuuno vremena.

2024-07-23 07:50 UTC, darrac requested changes
Mislim da ovom PR-u treba jos samo vremena i paznje. Osnovni principi su tu, ali imas krivo definirane velicine na fontovima, a po meni i na sidebaru.

2024-07-23 07:50 UTC, darrac commented on tvshows/src/app/layout.tsx
> +  const [isLargerThan768] = useMediaQuery("(min-width: 768px)");
I think an easier approach would be using something like: https://v2.chakra-ui.com/docs/components/show-hide with the above/below prop.

The breakpoints (base, sm, md, lg, xl) are already defined in the Chakra theme https://v2.chakra-ui.com/docs/styled-system/theme#breakpoints

2024-07-23 07:50 UTC, darrac commented on tvshows/src/app/layout.tsx
> +          <Box marginLeft={showSidebar && isLargerThan768 ? "30vh" : "0"}>
For responsive styles you can do something like: 
`marginLeft: { { base: 0, md: '40vw'} }`

https://v2.chakra-ui.com/docs/styled-system/responsive-styles

2024-07-23 07:50 UTC, darrac commented on tvshows/src/app/layout.tsx
> +          <Box marginLeft={showSidebar && isLargerThan768 ? "30vh" : "0"}>
Why is the inline (horizontal) margin defined by viewport height? That way the sidebar width changes when resizing the window vertically, which is weird.

2024-07-23 07:50 UTC, darrac commented on tvshows/src/components/features/review/ReviewList/ReviewList.tsx
> +        <Text textStyle="h2">Reviews</Text>
I see you replacing Headings with Text components. If you semantically need a Heading component, it is OK to use that, doesn't need to be Text. Of course, if semantically you want a Text component, use it.

2024-07-23 07:50 UTC, darrac commented on tvshows/src/theme/foundations/typography/textStyles.ts
> +    fontSize: ["54px", "70px"],
I have a feeling you got the font sizes wrong. The title is 40px with a line height of 52px on web and 23pc with a line height of 32px on mobile. Other sizes also seem to be off.
![image](https://github.com/user-attachments/assets/0678400f-d1a4-428d-a2db-179c840a444f)

2024-07-23 07:50 UTC, darrac commented on tvshows/src/theme/theme.ts
> +      ".authFormContainer": {
Are you using these classes at all?

2024-07-25 06:50 UTC, darrac approved these changes

2024-07-25 06:50 UTC, darrac commented on tvshows/src/components/shared/SidebarNavigation/MobileSidebarNavigation.tsx
> +                <Link href="/shows">
Did you intentionally switch form Link imported from `next` to the one imported from `chakra`? 
THe Chakra one gioves you styling, while the Next one gives you better navigation handling.

2024-07-25 06:50 UTC, darrac commented on tvshows/src/components/shared/SidebarNavigation/SidebarNavigation.tsx
> +        width="35vh"
I think I already mentioned this, but why are you basing the width of your navigation on the window **height**? I think it would make more sense to base it on the window width.

2024-07-27 16:57 UTC, korejur commented on tvshows/src/components/shared/SidebarNavigation/MobileSidebarNavigation.tsx
> +                <Link href="/shows">
Ups, nije namjerno bilo. Javlja mi se nekad hydration error zbog tih linkova pa sam se malo igrala s tim i očito krivo importala...

2024-07-29 07:28 UTC, darrac commented
Molim te samo da rijesis ovaj konflikt koji GH javlja pa da mozemo mergeati.
Mozes probati resolve conflict na githubu ili rucno mergeati main branch u homework-6 branch pa to pushati.

2024-07-29 13:09 UTC, merged